### ISSUE TITLE
FR - 参照Logseq对Zotero的处理？

### ISSUE THREAD

**Issue by sethyuan** [ahonn/logseq-plugin-weread-importer#4]
能否做成类似Logseq对Zotero导入的处理方式处理微信读书笔记的导入？也就是先让用户扫码登录微信读书，然后在键入特殊slash command时提供书籍搜索然后导入笔记并插入引用。

这里有微信读书API的参考：https://github.com/zhaohongxuan/obsidian-weread-plugin/blob/main/docs/weread-api.md。

**Comment by ahonn** [comment]
很好的建议。大概看了一下，目前 Logseq 的插件 API 看起来还实现不了扫码登陆，后面我研究看看有没有方法来实现。
